color_scheme:
    primary_normal: "#c4e1ff"
    primary_active: "#c4e1ff"
    primary_disabled: "#dddddd"
    secondary_normal: "#4fa6ff"
    secondary_active: "#4fa6ff"
    secondary_disabled: "#dddddd"
    background: "#ffffff"

file_types:
    - ["Trajectory Setup Files", "*.yaml"]
    - ["Trajectory Build Files", "*.traj"]
    - ["All Files", "*.*"]